Add support to upgrade to the latest version
cloud-bulldozer/benchmark-wrapper pull request #253
Opened 2021-02-18 14:32 UTC by chaitanyaenr

This commit:
- Adds an option to upgrade to the latest version available
  in the channel when set.
- Fixes linting issues.

2021-02-18 14:35 UTC, jtaleric commented on snafu/upgrade_openshift_wrapper/trigger_upgrade.py
> +            logging.error("Looks like both toimage and to_latest parameters are set, please set one of them")
Hm, should `toimage` just take president?

2021-02-18 14:35 UTC, jtaleric commented on snafu/upgrade_openshift_wrapper/trigger_upgrade.py
> +            logging.error("Looks like both toimage and to_latest parameters are set, please set one of them")
Actually.. thinking more, this is good.. just exit(1) here..

2021-02-18 14:36 UTC, jtaleric commented on snafu/upgrade_openshift_wrapper/upgrade_openshift_wrapper.py
> +            '--to_latest',
why `to_latest` vs `latest` ?

2021-02-18 14:36 UTC, jtaleric requested changes
one small nit.

2021-02-18 14:59 UTC, chaitanyaenr commented on snafu/upgrade_openshift_wrapper/upgrade_openshift_wrapper.py
> +            '--to_latest',
Switched to latest.

2021-02-18 19:12 UTC, chaitanyaenr commented
/rerun all

2021-02-18 19:20 UTC, jtaleric approved these changes
LGTM

2021-02-18 21:38 UTC, merged

2021-02-24 15:12 UTC, mohit-sheth commented
LGTM