Python 3.9 migration
cloud-bulldozer/benchmark-wrapper pull request #354
Opened 2021-09-15 14:12 UTC by rsevilla87

Signed-off-by: Raul Sevilla <rsevilla@redhat.com>

### Description

### Fixes

2021-09-17 18:09 UTC, jtaleric commented
@smalleni @mukrishn ```Status code: 404 for https://www.rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/rt-tests-1.9-2.el8.x86_64.rpm (IP: 195.220.108.108)
error building at STEP "RUN dnf -y install https://www.rpmfind.net/linux/centos/8-stream/AppStream/x86_64/os/Packages/rt-tests-1.9-2.el8.x86_64.rpm": error while running runtime: exit status 1```

2021-09-24 23:45 UTC, learnitall commented on snafu/flent_wrapper/Dockerfile
> +# Workaround: We need to download latest version of config.guess to make configure able to detect other CPU architectures correctly
Nice catch! I ran into this as well when debugging some of these builds. Glad to see this was included :)

2021-09-24 23:48 UTC, learnitall requested changes
@rsevilla87 since you're at it with upgrading to 3.9, can you also add in an extra line for these Dockerfiles to install dependencies from `requirements/py39-reqs/install.txt`? Also do we have any idea on what to do with the builds that are still failing? It would be great if we could get all these images fixed in this PR. For a temporary workaround on the 404 errors on cyclictest, I figured we could extract the rpm from our current images and store them under `snafu/image_resources`, then do the download from GH.

2021-09-27 12:21 UTC, rsevilla87 commented
> @rsevilla87 since you're at it with upgrading to 3.9, can you also add in an extra line for these Dockerfiles to install dependencies from `requirements/py39-reqs/install.txt`? Also do we have any idea on what to do with the builds that are still failing? It would be great if we could get all these images fixed in this PR. For a temporary workaround on the 404 errors on cyclictest, I figured we could extract the rpm from our current images and store them under `snafu/image_resources`, then do the download from GH.

I've updated the images for cyclitest and oslat to fedora, as those RPMs are not available in the official repositories anymore. Not sure if we want to move forward from here.

2021-09-28 15:52 UTC, learnitall approved these changes
Looks good to me! I'll adjust the build script to add ignores for certain architecture/image combinations (i.e. hammerdb on arm64). We can do the requirement files for the image stuffs.

2021-09-28 15:53 UTC, learnitall commented
/rerun all

2021-10-06 17:30 UTC, learnitall commented
/rerun all

2023-07-04 08:48 UTC, closed without merging